export { default as Home } from './Home'
export { default as Personality } from './Personality'
export { default as Skills } from './Skills'
export { default as Contact } from './Contact'
export { default as NotFound } from './NotFound'